apiVersion: v1
kind: Namespace
metadata:
  name: quant-platform-dev
  labels:
    name: quant-platform-dev
    environment: development
    app: quant-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quant-platform-dev-quota
  namespace: quant-platform-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: quant-platform-dev-limits
  namespace: quant-platform-dev
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
