server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 量化交易平台应用日志
  - job_name: quant-platform-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: quant-platform-app
          __path__: /var/log/quant-platform/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            component: component
            event_type: event_type
      - labels:
          level:
          logger:
          component:
          event_type:
      - timestamp:
          source: timestamp
          format: RFC3339

  # 交易日志
  - job_name: quant-platform-trading
    static_configs:
      - targets:
          - localhost
        labels:
          job: quant-platform-trading
          __path__: /var/log/quant-platform/trading.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            order_id: order_id
            symbol: symbol
            side: side
            order_type: order_type
            event_type: event_type
      - labels:
          level:
          order_id:
          symbol:
          side:
          order_type:
          event_type:
      - timestamp:
          source: timestamp
          format: RFC3339

  # 错误日志
  - job_name: quant-platform-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: quant-platform-errors
          __path__: /var/log/quant-platform/error.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            exception: exception
            component: component
      - labels:
          level:
          logger:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Docker容器日志
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

  # 系统日志
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)$'
      - labels:
          hostname:
          service:
      - timestamp:
          source: timestamp
          format: Jan 02 15:04:05

  # Nginx访问日志
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+)\s+-\s+(?P<remote_user>\S+)\s+\[(?P<time_local>[^\]]+)\]\s+"(?P<method>\S+)\s+(?P<request_uri>\S+)\s+(?P<server_protocol>\S+)"\s+(?P<status>\d+)\s+(?P<body_bytes_sent>\d+)\s+"(?P<http_referer>[^"]*)"\s+"(?P<http_user_agent>[^"]*)"'
      - labels:
          method:
          status:
          remote_addr:
      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700

  # PostgreSQL日志
  - job_name: postgresql
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgresql
          __path__: /var/log/postgresql/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d+\s+\S+)\s+\[(?P<pid>\d+)\]\s+(?P<level>\S+):\s+(?P<message>.*)$'
      - labels:
          level:
          pid:
      - timestamp:
          source: timestamp
          format: 2006-01-02 15:04:05.000 MST
